ExamenA/Apps/home/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView, InicioView, AdministradoresView, EstudiantesView, CrearComentarioArticuloView, AgregarEstudianteView
from Apps.home import views

from Apps.home.views import HomeView

app_name='home'

urlpatterns = [
    path('', HomeView.as_view(), name='indexapp'),
    path('Inicio', InicioView.as_view(), name='inicioapp'),
    path('Administradores', AdministradoresView.as_view(), name='administradoresapp'),
    path('Estudiantes/', EstudiantesView.as_view(), name='estudiantesapp'),
    path('Crear/', CrearComentarioArticuloView.as_view(), name='crearapp'),
    path('Agregar/', AgregarEstudianteView.as_view(), name='agregarapp'),
]

ExamenA/ExamenA/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('Apps.home.urls', 'index')),
]

ExamenA/Apps/home/models.py
from unittest.util import _MAX_LENGTH
from django.db import models

# Create your models here.

class Estudiantes(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=200)
    creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s %s' % (self.nombre,self.apellido)

class EstudiantesAprobacion(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=200)
    creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s %s' % (self.nombre,self.apellido)

class Articulo(models.Model):
    nombre = models.CharField(max_length=100)
    creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s' % (self.nombre)

class EstudiantesComunes(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=200)
    creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s %s' % (self.nombre,self.apellido)

class ComentarioArticulo(models.Model):
    Comentario = models.CharField(max_length=300)
    EstudiantesComunes = models.ForeignKey(EstudiantesComunes,on_delete=models.CASCADE)
    creacion = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return '%s' % (self.Comentario)

ExamenA/Apps/home/forms.py
from django import forms
from .models import ComentarioArticulo, Estudiantes

class ComentarioForm(forms.ModelForm):
    class Meta:
        model = ComentarioArticulo
        fields = '__all__'

class EstudiantesForm(forms.ModelForm):
    class Meta:
        model = Estudiantes
        fields = '__all__'

ExamenA/Apps/home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView
from .forms import ComentarioForm, EstudiantesForm
from django.urls import reverse_lazy

# Create your views here.

class HomeView(TemplateView):
    template_name='index.html'

class InicioView(TemplateView):
    template_name='inicio.html'

class AdministradoresView(TemplateView):
    template_name='Administradores.html'

class EstudiantesView(TemplateView):
    template_name='Estudiantes.html'
    

class CrearComentarioArticuloView(CreateView):
    template_name = 'CrearComentario.html'
    form_class = ComentarioForm
    success_url = reverse_lazy ('home:indexapp')

class AgregarEstudianteView(CreateView):
    template_name = 'AgregarEstudiante.html'
    form_class = EstudiantesForm
    success_url = reverse_lazy ('home:indexapp')

ExamenA/Apps/home/templates/Administradores.html
{% extends 'base.html '%}

{% block tablaA %}
<head>
<title>Tabla de administradores</title>
</head>

<body>
<div class="d- justify-content-center">
    <div class="text-center">
<table border="1" width="50%" bgcolor="white">
<thead bgcolor="aqua">
<tr>
<th>Nombre</th>
<th>Edad</th>
</tr>
</thead>

<tbody align="center">
<tr>
<td>Jose Perez</td>
<td>40</td>
</tr>

<tr>
<td>Raul Miranda</td>
<td>37</td>
</tr>

<tr>
<td>arnold Fuentes</td>
<td>55</td>
</tr>
</tbody>

</table>
</body>
{% endblock %}

{% block home %}
<h1><a href="{% url 'home:indexapp' %}" >Home</a></h1> 
{% endblock %}

ExamenA/Apps/home/templates/AgregarEstudiante.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AgregarEstudiante</title>
</head>
<body>
    {% block AgregarEstudiante %}
    
    <h1>Agregar Estudiante</h1>
    <form method="POST">
        {% csrf_token %}
        nombre {{ form.nombre }}
        apellido {{ form.apellido }}
        <input type="submit" name="GUARDAR">
    </form>
{% endblock %} 

{% block home %}
    <h1><a href="{% url 'home:indexapp' %}" >Home</a></h1> 
{% endblock %}
</body>
</html>

ExamenA/Apps/home/templates/CrearComentario.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulario</title>
</head>
<body>

{% block comentario %}
    <h1>Crear Comentario</h1>
    <form method="POST">
        {% csrf_token %}
        Comentario {{ form.Comentario }}
        EstudiantesComunes {{ form.EstudiantesComunes }}
        <input type="submit" name="GUARDAR">
    </form>
{% endblock %} 

{% block home %}
    <h1><a href="{% url 'home:indexapp' %}" >Home</a></h1> 
{% endblock %}
</body>
</html>

ExamenA/Apps/home/templates/Estudiantes.html
{% extends 'base.html '%}

{% block tabla %}
    <head>
    <title>Tabla de Estudiantes</title>
    </head>

    <body>
    <div class="d- justify-content-center">
        <div class="text-center">
    <table border="1" width="50%" bgcolor="white">
    <thead bgcolor="aqua">
    <tr>
    <th>Nombre</th>
    <th>Edad</th>
    <th>Carnet</th>
    </tr>
    </thead>

    <tbody align="center">
    <tr>
    <td>Luis Suarez</td>
    <td>22</td>
    <td>45893</td>
    </tr>

    <tr>
    <td>Leo Messi</td>
    <td>35</td>
    <td>36987</td>
    </tr>

    <tr>
    <td>Roni Coleman</td>
    <td>50</td>
    <td>35874</td>
    </tr>
    </tbody>

    </table>
    </div>
            </div>
    </body>
   
{% endblock %}
{% block home %}
<h1><a href="{% url 'home:indexapp' %}" >Home</a></h1> 
{% endblock %}

ExamenA/Apps/home/templates/Inicio.html
{% extends 'base.html' %}

{% block contenido %}
<h1 class="text-white mx-auto mt-2 mb-5">Inicio</h1>
<h2 class="text-white-50 mx-auto mt-2 mb-5">Esta es la actividad dos del curso de desarrollo web de la carrera de Ingenieria en Sitemnas 
    de la Universidad Mariano Galvez del Octavo Semestre </h2>
    <a href="{% url 'home:indexapp' %}">Home</a>

    {% endblock %}

ExamenA/Apps/home/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Grayscale - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#page-top">Start Bootstrap</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item"><a class="nav-link" href="#about">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="#projects">Projects</a></li>
                        <li class="nav-item"><a class="nav-link" href="#signup">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
                <div class="d-flex justify-content-center">
                    <div class="text-center">
                        <h1 class="mx-auto my-0 text--white-uppercase">-DESARROLLO WEB-</h1>
                        <h2 class="text-white-50 mx-auto mt-2 mb-5">Elder Antony Fuentes Fuentes</h2>
                        {% block tabla %}
                        {% endblock %}
                        {% block tablaA %}
                        {% endblock %}
                        {% block comentario %}
                        {% endblock %} 
                        {% block AgregarEstudiante %}
                        {% endblock %} 
                    </div>
                </div>
            </div>
        </header>
        <!-- About-->
        <section class="about-section text-center" id="about">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-8">
                        {% block home %}

                        {% endblock %}
                        {% block contenido %}

                        {% endblock %}
                        <h2 class="text-white mb-4"></h2>
                        <p class="text-white-50">
                        </p>
                    </div>
                </div>
                <img class="img-fluid" src="assets/img/ipad.png" alt="..." />
            </div>
        </section>
        <!-- Projects-->

        <section class="projects-section bg-light" id="projects">
            <div class="container px-4 px-lg-5">
                <!-- Featured Project Row-->
                <div class="row gx-0 mb-4 mb-lg-5 align-items-center">
                    <div class="col-xl-8 col-lg-7"><img class="img-fluid mb-3 mb-lg-0" src="assets/img/bg-masthead.jpg" alt="..." /></div>
                    <div class="col-xl-4 col-lg-5">
                        <div class="featured-text text-center text-lg-left">
                            <h4>Shoreline</h4>
                            <p class="text-black-50 mb-0">Grayscale is open source and MIT licensed. This means you can use it for any project - even commercial projects! Download it, customize it, and publish your website!</p>
                        </div>
                    </div>
                </div>
                <!-- Project One Row-->
                <div class="row gx-0 mb-5 mb-lg-0 justify-content-center">
                    <div class="col-lg-6"><img class="img-fluid" src="assets/img/demo-image-01.jpg" alt="..." /></div>
                    <div class="col-lg-6">
                        <div class="bg-black text-center h-100 project">
                            <div class="d-flex h-100">
                                <div class="project-text w-100 my-auto text-center text-lg-left">
                                    <h4 class="text-white">Misty</h4>
                                    <p class="mb-0 text-white-50">An example of where you can put an image of a project, or anything else, along with a description.</p>
                                    <hr class="d-none d-lg-block mb-0 ms-0" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Project Two Row-->
                <div class="row gx-0 justify-content-center">
                    <div class="col-lg-6"><img class="img-fluid" src="assets/img/demo-image-02.jpg" alt="..." /></div>
                    <div class="col-lg-6 order-lg-first">
                        <div class="bg-black text-center h-100 project">
                            <div class="d-flex h-100">
                                <div class="project-text w-100 my-auto text-center text-lg-right">
                                    <h4 class="text-white">Mountains</h4>
                                    <p class="mb-0 text-white-50">Another example of a project with its respective description. These sections work well responsively as well, try this theme on a small screen!</p>
                                    <hr class="d-none d-lg-block mb-0 me-0" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        

        <!-- Signup-->
        <section class="signup-section" id="signup">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5">
                    <div class="col-md-10 col-lg-8 mx-auto text-center">
                        <i class="far fa-paper-plane fa-2x mb-2 text-white"></i>
                        <h2 class="text-white mb-5">Subscribe to receive updates!</h2>
                        <!-- * * * * * * * * * * * * * * *-->
                        <!-- * * SB Forms Contact Form * *-->
                        <!-- * * * * * * * * * * * * * * *-->
                        <!-- This form is pre-integrated with SB Forms.-->
                        <!-- To make this form functional, sign up at-->
                        <!-- https://startbootstrap.com/solution/contact-forms-->
                        <!-- to get an API token!-->
                        <form class="form-signup" id="contactForm" data-sb-form-api-token="API_TOKEN">
                            <!-- Email address input-->
                            <div class="row input-group-newsletter">
                                <div class="col"><input class="form-control" id="emailAddress" type="email" placeholder="Enter email address..." aria-label="Enter email address..." data-sb-validations="required,email" /></div>
                                <div class="col-auto"><button class="btn btn-primary disabled" id="submitButton" type="submit">Notify Me!</button></div>
                            </div>
                            <div class="invalid-feedback mt-2" data-sb-feedback="emailAddress:required">An email is required.</div>
                            <div class="invalid-feedback mt-2" data-sb-feedback="emailAddress:email">Email is not valid.</div>
                            <!-- Submit success message-->
                            <!---->
                            <!-- This is what your users will see when the form-->
                            <!-- has successfully submitted-->
                            <div class="d-none" id="submitSuccessMessage">
                                <div class="text-center mb-3 mt-2 text-white">
                                    <div class="fw-bolder">Form submission successful!</div>
                                    To activate this form, sign up at
                                    <br />
                                    <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                                </div>
                            </div>
                            <!-- Submit error message-->
                            <!---->
                            <!-- This is what your users will see when there is-->
                            <!-- an error submitting the form-->
                            <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3 mt-2">Error sending message!</div></div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <!-- Contact-->
        <section class="contact-section bg-black">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5">
                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100">
                            <div class="card-body text-center">
                                <i class="fas fa-map-marked-alt text-primary mb-2"></i>
                                <h4 class="text-uppercase m-0">Address</h4>
                                <hr class="my-4 mx-auto" />
                                <div class="small text-black-50">4923 Market Street, Orlando FL</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100">
                            <div class="card-body text-center">
                                <i class="fas fa-envelope text-primary mb-2"></i>
                                <h4 class="text-uppercase m-0">Email</h4>
                                <hr class="my-4 mx-auto" />
                                <div class="small text-black-50"><a href="#!">hello@yourdomain.com</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100">
                            <div class="card-body text-center">
                                <i class="fas fa-mobile-alt text-primary mb-2"></i>
                                <h4 class="text-uppercase m-0">Phone</h4>
                                <hr class="my-4 mx-auto" />
                                <div class="small text-black-50">+1 (555) 902-8832</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="social d-flex justify-content-center">
                    <a class="mx-2" href="#!"><i class="fab fa-twitter"></i></a>
                    <a class="mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
                    <a class="mx-2" href="#!"><i class="fab fa-github"></i></a>
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="footer bg-black small text-center text-white-50"><div class="container px-4 px-lg-5">Copyright &copy; Your Website 2022</div></footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

ExamenA/Apps/home/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Examen</title>
</head>
<body>
    <h1>Pagina principal de la app</h1>
    <a href="{% url 'home:Inicioapp' %}">Inicio</a>
</body>
</html>

ExamenA/Apps/home/templates/index.html
{% extends 'base.html' %}

{% block contenido %}
    <h1 class="text-white">Home</h1>
    <a href="{% url 'home:inicioapp' %}">Inicio</a>
	<a href="{% url 'home:estudiantesapp' %}">Estudiantes</a>
	<a href="{% url 'home:administradoresapp' %}">Administradores</a>
    <a href="{% url 'home:crearapp' %}">Crear Comentario</a>
    <a href="{% url 'home:agregarapp' %}">Agregar Estudiante</a>
{% endblock %} 